@extends('layouts.app')
@section('title', "Home Page")
@section('content')
<h1>Giới Thiệu</h1>
<p>Tiệm Bánh Xinh được ra đời với thông điệp mang đam mê của chúng tôi gửi gắm đến bạn qua những chiếc bánh ngọt và thức uống ngon, giá rẻ, vệ sinh và chất lượng luôn được đặt lên hàng đầu. Sự ra đời của mỗi chiếc bánh đều được chọn lọc kỹ lưỡng tâm huyết của đội ngũ chúng tôi từ khâu nguyên liệu, chế biến để khi đến tay của các bạn, chúng đều trở thành sản phẩm hoàn hảo nhất</p>
<p>Với không gian đẹp, yên tĩnh, Tiệm Bánh Xinh thích hợp là nơi để bạn có thể thư giãn sau những giờ học tập và làm việc mệt mỏi, nơi bạn có thể vừa thưởng thức bánh ngọt vừa tán gẫu những câu chuyện vui vẻ cùng bạn bè, hay chỉ đơn giản bạn cần một tách cà phê và một chiếc bánh ngọt cùng với quyển sách bạn yêu thích. Và là thiên đường đối với những tín đồ thích ăn ngọt.</p>
<h3>MÔ HÌNH PHƯƠNG TÂY</h3>
<p>Tiệm Bánh Xinh được xây dựng và hoạt động theo mô hình phương Tây. Mỗi chiếc bánh được làm ra với phong cách mang đậm hương vị đến từ Pháp và Mỹ - hai đất nước nổi tiếng tiên phong trong việc cho ra đời những món tráng miệng ngon và đẹp mắt bậc nhất thế giới.</p>
<p>Trong những năm trở lại đây, bánh Pháp và Mỹ được xếp vào loại những loại tráng miệng ngon nhất thế giới, các loại bánh ngon đến từ hai đất nước này đang ngày một chiếm gần tình cảm và được giới trẻ Việt Nam ưa chuộng. Vì thế, để thỏa mãn được nhu cầu thưởng thức của các bạn trẻ, Tiệm Bánh Xinh luôn học hỏi và cập nhật những loại bánh mới nhất, được giới trẻ ở phương Tây ưa chuộng bên cạnh làm ra những chiếc bánh đã nổi tiếng từ lâu, những chiếc bánh ngọt, bánh mặn mà khiến bạn chỉ nhìn thôi cũng đã thấy… no! Do đó để được “ngon mắt” và “đã miệng”, hãy mau đến với chúng tôi để trải nghiệm sự kết hợp hài hòa phương Tây giữa Pháp và Mỹ các bạn ơi !!!</p>
<h3>PHÁP: VẺ ĐẸP THƠ MỘNG NƠI NHỮNG CHIẾC BÁNH</h3>
<p>Nổi tiếng là đất nước mộng mơ, lãng mạn, trung tâm văn hóa – nghệ thuật Châu Âu, kinh đô thời trang thế giới và là nơi có nền ẩm thực vô cùng độc đáo, nước Pháp dễ dàng quyến rũ và chinh phục bất cứ du khách nào đặt chân tới, dù là những thực khách khó tính nhất. Đến với Pháp, bạn sẽ được chiêm ngưỡng vô vàn cảnh đẹp nên thơ như kinh đô của ánh sáng và tình yêu Paris hay hàng loạt chuỗi cửa hàng thời trang và đồ hiệu danh giá bậc nhất thế giới tại Khải Hoàn Môn hay những âm thanh ào ào của thác đổ.</p>
<p>Và đến với Pháp, bạn sẽ tìm thấy ở đó một tiêu chuẩn trong ẩm thực rất cao: những chai rượu vang cao cấp đắt đỏ hay những dắt bò beefsteak thơm phức. Chưa dừng lại ở đó, Pháp còn nổi tiếng với hương vị xa xỉ và vẻ đẹp bắt mắt của nhưng món tráng miệng, trong đó có những chiếc bánh. Bánh Red Velet – chiếc bánh của tình yêu mang màu đỏ nồng nàn, say đắm được giới trẻ Pháp ưa dùng trong dịp lễ tình yêu Valentine hay bánh Crepe, bánh Macaron, bánh Opera… những chiếc bánh đẹp mắt, hấp dẫn với hương vị ngọt ngào sẽ dễ dàng khơi dậy và đánh thức mọi giác quan của bạn đấy nha!!!</p>
@endsection
